language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

jobs:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 7.4snapshot

before_script:
  - composer self-update
  - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
